image: docker:19.03.13

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
 
build:
  stage: build
  before_script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t "$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA" .
    - docker push "$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA"
