
stages:
  - build
  - test
  - deploy



variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.13-dind


test_variable:
  stage: build
  script:
    - echo "$AWS_USERNAME"
    - echo "$AWS_ECR_PASS"
    - echo "$AWS_ACCOUNT_ID"



# build:
#   stage: build
#   image: docker:19.03.13
#   before_script:
#     - docker login --username ${AWS_USERNAME} --password ${AWS_ECR_PASS} '${AWS_ACCOUNT_ID}.dkr.ecr.region.amazonaws.com'
#   script:
#     - docker build -t ${DOCKER_IMAGE_NAME} .
#     - docker push ${DOCKER_IMAGE_NAME}
