
stages:
  - build
  - test
  - deploy



variables:
  DOCKER_TLS_CERTDIR: "/certs"
  AWS_REPO_URL: "$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
  

services:
  - docker:19.03.13-dind
  - amazon/aws-cli



build:
  stage: build
  image: docker:19.03.13
  before_script:
    - aws --version
    - echo ${AWS_REPO_URL}
    - docker login --username ${AWS_USERNAME} --password ${AWS_ECR_PASS} $AWS_REPO_URL
  script:
    - docker build -t "$AWS_REPO_URL/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA" .
    - docker push "$AWS_REPO_URL/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA"
